config/routes.rb
Rails.application.routes.draw do
  resources :results do
    collection { post :import }
  end
  root  'results#index'

end

app/models/result.rb
class Result < ActiveRecord::Base

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Result.create! row.to_hash
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    if params[:search]
      @results = Result.where("cname LIKE ?", "%#{params[:search]}%")
    else
      @results = Result.all
    end
  end

  def import
    Result.import(params[:file])
    redirect_to root_url, notice: "Results Imported."
  end


  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:rno, :cname, :fname)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rno %><br>
    <%= f.number_field :rno %>
  </div>
  <div class="field">
    <%= f.label :cname %><br>
    <%= f.text_field :cname %>
  </div>
  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Search Online Result of S.S.T (General) Male (B-17)</h3>
<br>

<%= form_tag results_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search], placeholder: "Search by Name Only", class: "search-field" %>
    <%= submit_tag "Search", :name => nil, class: "btn-search" %>
  </p>
<% end %>

<br><br>

<% if params[:search].present? %>
 <% if @results.present? %>
<table>
  <thead>
    <tr>
      <th>S.No</th>
      <th>Roll Number</th>
      <th>Name</th>
      <th>Father Name</th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.id %></td>
        <td><%= result.rno %></td>
        <td><%= result.cname %></td>
        <td><%= result.fname %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  <% else %>
<p class="no-result"> 
  There is no such result found with <b class="params-search"><%= params[:search] %></b>...!!!
</p>
  <% end %>
<% else %>
<p>
  There is no result searched yet...
</p>
<% end %>
<br><br>
<!--
<%= form_tag import_results_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<br><br>
<%= link_to 'New Result', new_result_path %>
-->

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rno:</strong>
  <%= @result.rno %>
</p>

<p>
  <strong>Cname:</strong>
  <%= @result.cname %>
</p>

<p>
  <strong>Fname:</strong>
  <%= @result.fname %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>